version: "3.7"
services:
  mariadb:
    image: mariadb:10.3.13
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dop
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
